//
//  CardInsightSection.swift
//  Dayflow
//
//  The "How Dayflow figured this out" panel shown inside an activity card's detail
//  view. Collapsed by default to keep the card clean; expands to show the model's
//  reasoning, the on-screen observations it wrote, which model ran, and an optional
//  raw LLM-call view for power users. See CardInsight for the data.
//

import ImageIO
import SwiftUI

struct CardInsightSection: View {
  let insight: CardInsight

  @State private var expanded = false
  @State private var showRaw = false

  private let labelColor = Color(red: 0.55, green: 0.55, blue: 0.55)
  private let bodyColor = Color(red: 0.15, green: 0.15, blue: 0.15)

  var body: some View {
    VStack(alignment: .leading, spacing: 10) {
      header

      if expanded {
        if !insight.reasoningSteps.isEmpty {
          VStack(alignment: .leading, spacing: 10) {
            ForEach(insight.reasoningSteps) { step in
              VStack(alignment: .leading, spacing: 2) {
                Text(step.label.uppercased())
                  .font(Font.custom("Figtree", size: 10).weight(.semibold))
                  .foregroundColor(labelColor)
                Text(step.text)
                  .font(Font.custom("Figtree", size: 12))
                  .foregroundColor(bodyColor)
                  .fixedSize(horizontal: false, vertical: true)
                  .textSelection(.enabled)
              }
            }
          }
        }

        if !insight.observations.isEmpty {
          observationsView
        }

        footer

        if !insight.rawCalls.isEmpty {
          rawToggle
          if showRaw {
            VStack(alignment: .leading, spacing: 6) {
              ForEach(insight.rawCalls) { call in
                RawCallRow(call: call)
              }
            }
          }
        }
      }
    }
    .padding(.top, 2)
  }

  private var header: some View {
    Button {
      withAnimation(.easeOut(duration: 0.18)) { expanded.toggle() }
    } label: {
      HStack(spacing: 6) {
        Image(systemName: "sparkles")
          .font(.system(size: 10, weight: .semibold))
          .foregroundColor(labelColor)
        Text("HOW DAYFLOW FIGURED THIS OUT")
          .font(Font.custom("Figtree", size: 12).weight(.semibold))
          .foregroundColor(labelColor)
        Spacer(minLength: 6)
        Image(systemName: "chevron.down")
          .font(.system(size: 9, weight: .semibold))
          .foregroundColor(labelColor)
          .rotationEffect(.degrees(expanded ? 0 : -90))
      }
      .contentShape(Rectangle())
    }
    .buttonStyle(.plain)
    .pointingHandCursor()
  }

  private var observationsView: some View {
    VStack(alignment: .leading, spacing: 8) {
      Text("WHAT IT SAW ON SCREEN")
        .font(Font.custom("Figtree", size: 10).weight(.semibold))
        .foregroundColor(labelColor)
      ForEach(insight.observations) { obs in
        HStack(alignment: .top, spacing: 9) {
          if let path = obs.screenshotPath {
            ObservationThumbnail(path: path)
          }
          VStack(alignment: .leading, spacing: 2) {
            Text(obs.time)
              .font(Font.custom("Figtree", size: 11).weight(.medium).monospacedDigit())
              .foregroundColor(labelColor)
            Text(obs.text)
              .font(Font.custom("Figtree", size: 12))
              .foregroundColor(bodyColor)
              .fixedSize(horizontal: false, vertical: true)
              .textSelection(.enabled)
          }
        }
      }
    }
  }

  @ViewBuilder
  private var footer: some View {
    if insight.model != nil || insight.provider != nil {
      let parts = [insight.model, insight.provider].compactMap { $0 }
      HStack(spacing: 5) {
        Image(systemName: "cpu")
          .font(.system(size: 10, weight: .medium))
          .foregroundColor(labelColor)
        Text("Generated by \(parts.joined(separator: " · "))")
          .font(Font.custom("Figtree", size: 11))
          .foregroundColor(labelColor)
      }
    }
  }

  private var rawToggle: some View {
    Button {
      withAnimation(.easeOut(duration: 0.15)) { showRaw.toggle() }
    } label: {
      HStack(spacing: 5) {
        Image(systemName: showRaw ? "chevron.down" : "chevron.right")
          .font(.system(size: 8, weight: .semibold))
        Text(showRaw ? "Hide raw LLM calls" : "Show raw LLM calls (\(insight.rawCalls.count))")
          .font(Font.custom("Figtree", size: 11).weight(.medium))
      }
      .foregroundColor(labelColor)
      .contentShape(Rectangle())
    }
    .buttonStyle(.plain)
    .pointingHandCursor()
  }
}

/// One raw LLM call: a tappable header (operation · status · latency) that expands
/// to show the response body. Request bodies aren't shown — image payloads aren't
/// logged, and the response is what carries the model's actual output.
private struct RawCallRow: View {
  let call: CardInsight.RawCall
  @State private var open = false

  private let labelColor = Color(red: 0.55, green: 0.55, blue: 0.55)

  var body: some View {
    VStack(alignment: .leading, spacing: 4) {
      Button {
        withAnimation(.easeOut(duration: 0.12)) { open.toggle() }
      } label: {
        HStack(spacing: 6) {
          Circle()
            .fill(call.status == "success" ? Color.green.opacity(0.7) : Color.red.opacity(0.7))
            .frame(width: 6, height: 6)
          Text(call.operation)
            .font(Font.custom("Figtree", size: 11).weight(.semibold).monospaced())
            .foregroundColor(Color(red: 0.25, green: 0.25, blue: 0.25))
          Spacer(minLength: 6)
          if let ms = call.latencyMs {
            Text("\(ms) ms")
              .font(Font.custom("Figtree", size: 10).monospacedDigit())
              .foregroundColor(labelColor)
          }
        }
        .contentShape(Rectangle())
      }
      .buttonStyle(.plain)
      .pointingHandCursor()

      if open, let body = displayBody {
        ScrollView {
          Text(body)
            .font(.system(size: 10.5, design: .monospaced))
            .foregroundColor(Color(red: 0.2, green: 0.2, blue: 0.2))
            .frame(maxWidth: .infinity, alignment: .leading)
            .textSelection(.enabled)
            .padding(8)
        }
        .frame(maxHeight: 220)
        .background(Color.black.opacity(0.035))
        .clipShape(RoundedRectangle(cornerRadius: 6, style: .continuous))
      }
    }
  }

  private var displayBody: String? {
    guard let raw = call.responseBody?.trimmingCharacters(in: .whitespacesAndNewlines),
      !raw.isEmpty
    else { return call.status == "success" ? nil : "(no response body)" }
    let limit = 4000
    return raw.count > limit ? String(raw.prefix(limit)) + "\n… (truncated)" : raw
  }
}

/// A small downsampled screenshot for an observation row. Loads off the main
/// thread via ImageIO so the detail panel stays smooth even with many frames.
private struct ObservationThumbnail: View {
  let path: String
  @State private var image: NSImage?

  var body: some View {
    ZStack {
      RoundedRectangle(cornerRadius: 4, style: .continuous)
        .fill(Color.black.opacity(0.05))
      if let image {
        Image(nsImage: image)
          .resizable()
          .scaledToFill()
      }
    }
    .frame(width: 54, height: 34)
    .clipShape(RoundedRectangle(cornerRadius: 4, style: .continuous))
    .overlay(
      RoundedRectangle(cornerRadius: 4, style: .continuous)
        .strokeBorder(Color.black.opacity(0.08), lineWidth: 0.5)
    )
    .task(id: path) {
      let p = path
      let loaded = await Task.detached(priority: .utility) {
        ObservationThumbnail.downsample(path: p, maxPixel: 160)
      }.value
      await MainActor.run { image = loaded }
    }
  }

  static func downsample(path: String, maxPixel: CGFloat) -> NSImage? {
    let url = URL(fileURLWithPath: path)
    guard let source = CGImageSourceCreateWithURL(url as CFURL, nil) else { return nil }
    let options: [CFString: Any] = [
      kCGImageSourceCreateThumbnailFromImageAlways: true,
      kCGImageSourceCreateThumbnailWithTransform: true,
      kCGImageSourceShouldCacheImmediately: true,
      kCGImageSourceThumbnailMaxPixelSize: maxPixel,
    ]
    guard let cg = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else {
      return nil
    }
    return NSImage(cgImage: cg, size: NSSize(width: cg.width, height: cg.height))
  }
}
